# Generated by Django 2.1 on 2018-08-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denon_code', models.CharField(max_length=10)),
                ('readable_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('queryable', models.BooleanField(default=False)),
                ('icon_code', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denon_code', models.CharField(max_length=25)),
                ('readable_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_code', models.CharField(blank=True, max_length=25, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Command')),
            ],
        ),
    ]
