# Generated by Django 2.1 on 2018-08-17 16:40

import os

from django.db import migrations
from django.conf import settings
from django.core import serializers


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        initial_data_file_path = os.path.join(settings.BASE_DIR, 'api', 'fixtures', 'initial_data.json')
        with open(initial_data_file_path) as initial_data_file:
            objects = serializers.deserialize('json', initial_data_file, ignorenonexistent=True)
            for obj in objects:
                obj.save()

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
